### ISSUE TITLE
missing license file for Apache-2.0

### ISSUE THREAD

**Issue by decathorpe** [vi/timeago#30]
Hi! I'm working on packaging this crate for Fedora Linux since it is a new dependency of *eza* (a maintained *exa* fork). During technical review, we noticed that this crate's metadata states that the license is "MIT/Apache-2.0", but the license text only contains the MIT license.

Please also include a copy of the Apache-2.0 license text (the idiomatic way to handle this in Rust crates seems to be to have both `LICENSE-MIT` and `LICENSE-APACHE` files). Both the MIT and the Apache-2.0 license require redistributed sources to contain a copy of the license text, so the missing license text is currently preventing us from packaging *eza*.

**Comment by vi** [comment]
@decathorpe Pull request that adds proper `LICENSE-MIT` and `LICENSE-APACHE` files is welcome.

Do I need to create another tag/version with just the licence files changes?

**Comment by decathorpe** [comment]
Having the license file in the git repo would be enough for me to reference it, but having a new release would be even better. 👍🏼

**Comment by vi** [comment]
Released 0.4.2 with the licence file fix.

**Comment by decathorpe** [comment]
Thank you! 👍🏼
